name: sendmail
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 587
          # Optional (recommended): mail server username:
          username: "ershivamksingh@gmail.com"
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: shivamsam8115@gmail.com
          # Required sender full name (address can be skipped):
          from: Shivam Singh # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: false
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional carbon copy recipients:
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional attachments:
          attachments: ansible/test/site.yml
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
