# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
#     environment: DEV
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Run ansible playbook
        env:
          SECRET_1: ${{ secrets.SECRET_TEST }}
        run: |
          sed -i 's/_SECRET_1/${{ env.SECRET_1 }}/g' ./ansible/test/roles/hello-world/vars/main.yml
          ansible-playbook ./ansible/test/site.yml -e test_1=1 -e test_2=2
          
      - id: sets-a-secret
        run: |
          my_secret=$((RANDOM))
          echo "::add-mask::$my_secret"
          echo "::set-output name=secret::$my_secret"
      - run: |
          echo default step display name will the secret ${{ steps.sets-a-secret.outputs.secret }}
      - id: ouput_1
        run: |
          echo "::set-output name=secret::testing"
    outputs:
      output: "${{ steps.ouput_1.outputs.secret }}"
